routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('/login');
Route::get('/', 'Admin\Auth\LoginController@showLoginForm')->name('/');
Route::post('/loggedin', 'Admin\Auth\LoginController@login');
Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@otpRequestForm')->name('password.reset');
Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendOTP')->name('password.email');
Route::get('password/otp', 'Admin\Auth\ForgotPasswordController@otpForm')->name('password.otp');
Route::get('password/otpvarify', 'Admin\Auth\ForgotPasswordController@otpVarification')->name('password.otpvarify');
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	Route::resource('dashboard', 'Dashboard\DashboardController');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');

	Route::resource('service', 'Service\ServiceTypeController');

	Route::resource('vehicle', 'Vehicle\VehicleController');
	Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');
	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	Route::get('driver/carimages/{id}', 'Driver\DriverController@driverCarImages')->name('driver.carimages');
	Route::get('driver/transaction/{id}', 'Driver\DriverController@driverTransaction')->name('driver.transaction');
	Route::post('driver/document-reason/{id}', 'Driver\DriverController@documentVerificationReason')->name('driver.document-reason');

	Route::resource('credit', 'CreditPackage\CreditPackageController');
	Route::resource('setting', 'Setting\SettingController');
	Route::resource('email-control', 'Email\EmailController');

	//Driver Document verification.........

	Route::get('driver/check-document/{id}', 'Driver\DocumentVerificationController@allDocumentCheck')->name('driver.check-document');
	Route::get('driver/rating-review/{id}', 'Driver\DriverRatingController@driverRatingReview')->name('driver.rating-review');
	Route::get('driver/runcron/{id}', 'Driver\DocumentVerificationController@cronjobToMailDriver')->name('driver.runcron');
	//.....................................

	Route::get('driver/rating-list/{id}/{last_id}/{first_id}', 'Driver\DriverRatingController@ratingList')->name('driver.rating-list');
	Route::post('driver/reason/{id}', 'Driver\DriverController@driverInactiveBannedReason')->name('driver.reason');
	Route::get('driver/rating-search/{id}', 'Driver\DriverRatingController@searchRating')->name('driver.rating-search');

	Route::post('driver/rating-alert/{id}', 'Driver\DriverRatingController@driverRatingAlert')->name('driver.rating-alert');
	//payment
	// Route::get('payment/index', 'Payment\PaymentController@paymentList')->name('payment.index');

	Route::get('package/sales/report', 'PackageSales\PackageSalesReportController@packageSalesReport')->name('package.sales.report');
	Route::get('package/sales/report/search', 'PackageSales\PackageSalesReportController@searchPackageSalesReport')->name('package.sales.report.search');
	Route::get('package/sales/report/details/{id}', 'PackageSales\PackageSalesReportController@packageSalesReportDetails')->name('package.sales.report.details');
	Route::get('package/sales/report/detail/{id}/{from_date}/{to_date}', 'PackageSales\PackageSalesReportController@packageSalesReportDetailsBySearch')->name('package.sales.report.detail');

	//ride history
	Route::get('statement/{type}', 'Statement\StatementController@statement')->name('statement');
		//not use
		Route::get('statement/today', 'Statement\StatementController@statement_today')->name('statement.today');
		Route::get('statement/weekly', 'Statement\StatementController@statement_weekly')->name('statement.weekly');
		Route::get('statement/monthly', 'Statement\StatementController@statement_monthly')->name('statement.monthly');
		Route::get('statement/yearly', 'Statement\StatementController@statement_yearly')->name('statement.yearly');
		//not use
	Route::post('ajax-statement','Statement\StatementController@ajaxStatement')->name('ajax-statement');
	//............
	Route::get('statement/details/{id}/{param}', 'Statement\StatementController@rideDetails')->name('statement.details');

	Route::get('statement/driver/index', 'Statement\StatementController@driverStatementIndex')->name('statement.driver.index');
	Route::post('ajax-driver-statement','Statement\StatementController@ajaxDriverStatement')->name('ajax-driver-statement');
	Route::get('statement/driver/details/{id}', 'Statement\StatementController@driverStatementDetails')->name('statement.driver.details');
	Route::get('statement/driver/detailsbybid/{id}', 'Statement\StatementController@driverStatementDetailsByBid')->name('statement.driver.detailsbybid');
	
	Route::resource('promocode', 'Promocode\PromocodeController');

	Route::get('report-issue/bydriver', 'ReportIssue\ReportIssueController@reportedByDriver')->name('report-issue.bydriver');
	Route::get('report-issue/bypassenger', 'ReportIssue\ReportIssueController@reportedByPassenger')->name('report-issue.bypassenger');
	Route::get('report-issue/details/{id}/{param}', 'ReportIssue\ReportIssueController@reportIssueDetails')->name('report-issue.details');

	Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');

	Route::get('passenger/delete/{id}', 'Passenger\PassengerController@deletePassenger')->name('passenger.delete');

	Route::get('driver/delete/{id}', 'Driver\DriverController@deleteDriver')->name('driver.delete');

});

app/Http/Controllers/Admin/Statement/StatementController.php
<?php

namespace App\Http\Controllers\Admin\Statement;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Model\Request\WaypointRequest;
use App\Model\Request\PassengerRequest;
use App\User;
use App\Model\Request\BidRequest;
use \Carbon\Carbon;
use Exception;


class StatementController extends Controller
{
	public function rideDetails($id,$param)
	{
		$passengerRequest = PassengerRequest::find($id);
		$passenger = User::find($passengerRequest->passenger_id);
		$driver = User::find($passengerRequest->driver_id);
		$waypoints=WaypointRequest::where('passenger_request_id', $id)->get();
			$source_address=null;
			$source_long=null;
			$source_lat=null;
			$destination_address=null;
			$destination_long=null;
			$destination_lat=null;
			foreach ($waypoints as $key => $waypoint) {
				if ($waypoint->waypoint_type=='source') {
					$source_address = $waypoint->address;
					$source_long = $waypoint->longitude;
					$source_lat = $waypoint->latitude;
				}
				if ($waypoint->waypoint_type=='destination') {
					$destination_address = $waypoint->address;
					$destination_long = $waypoint->longitude;
					$destination_lat = $waypoint->latitude;
				}
			}

		return view('admin.statements.request', compact('passengerRequest','passenger','driver','source_address','source_long','source_lat','destination_address','destination_long','destination_lat','param'));
	}

	public function driverStatementIndex1()
	{
		$drivers = User::where('user_scope', 'driver-service')->orWhere('user_scope', 'driver-passenger-service')->orderBy('created_at' , 'desc')->get();
		
		foreach ($drivers as $key => $driver) {
			$passengerRequests = PassengerRequest::where('driver_id',$driver->id)->get();

			$driver->totalRide=count($passengerRequests);
			$totalEarn=null;
			foreach ($passengerRequests as $key => $passengerRequest) {
				if ($passengerRequest->request_status=='Completed') {
					$bidRequest = BidRequest::where('passenger_request_id',$passengerRequest->passenger_request_id)->where('driver_id',$passengerRequest->driver_id)->first();
					if (isset($bidRequest)) {
						$totalEarn = $totalEarn+$bidRequest->bid_cost;
					}
				}
				$driver->totalEarn = $totalEarn;
			}
		}
		
		return view('admin.statements.driver-statement', compact('drivers'));
	}


	public function driverStatementIndex()
	{
		return view('admin.statements.driver-statement');
	}

	public function ajaxDriverStatement(Request $request)
	{
		$columns = array(
            0 => 'first_name',
			//1 => 'last_name',
			1 => 'isdCode',
			// 1 => 'mobile',
			5 => 'created_at',
		);
		
		$limit = $request->input('length');
		$start = $request->input('start');
		$order = $columns[$request->input('order.0.column')];
		$dir = $request->input('order.0.dir');

        $totalDrivers = User::where('user_scope', 'driver-service')->orWhere('user_scope', 'driver-passenger-service')->count();
		
		if(empty($request->input('search.value'))){
			$drivers = User::where('user_scope', 'driver-service')->orWhere('user_scope', 'driver-passenger-service')->offset($start)
					->limit($limit)
					->orderBy($order,$dir)
					->get();
			foreach ($drivers as $key => $driver) {
				$passengerRequests = PassengerRequest::where('driver_id',$driver->id)->get();
				$driver->totalRide=count($passengerRequests);
				$totalEarn=null;
				foreach ($passengerRequests as $key => $passengerRequest) {
					if ($passengerRequest->request_status=='Completed') {
						$bidRequest = BidRequest::where('passenger_request_id',$passengerRequest->passenger_request_id)->where('driver_id',$passengerRequest->driver_id)->first();
						if (isset($bidRequest)) {
							$totalEarn = $totalEarn+$bidRequest->bid_cost;
						}
					}
					$driver->totalEarn = $totalEarn;
				}
			}
			
			$totalFiltered = User::where('user_scope', 'driver-service')->orWhere('user_scope', 'driver-passenger-service')->count();
		}else{
			$search = $request->input('search.value');
            $drivers = User::where('user_scope', 'driver-service')
            	->where(function($q) use ($search){
					$q->where('first_name', 'like', "%{$search}%")
	                ->orWhere('last_name', 'like', "%{$search}%")
					->orWhere('isdCode','like',"%{$search}%")
					->orWhere('mobile','like',"%{$search}%")
					->orWhere('created_at','like',"%{$search}%");
				})
				->orWhere('user_scope', 'driver-passenger-service')
				->where(function($q) use ($search){
					$q->where('first_name', 'like', "%{$search}%")
	                ->orWhere('last_name', 'like', "%{$search}%")
					->orWhere('isdCode','like',"%{$search}%")
					->orWhere('mobile','like',"%{$search}%")
					->orWhere('created_at','like',"%{$search}%");
				})
				->offset($start)
				->limit($limit)
				->orderBy($order, $dir)
				->get();

			foreach ($drivers as $key => $driver) {
				$passengerRequests = PassengerRequest::where('driver_id',$driver->id)->get();
				$driver->totalRide=count($passengerRequests);
				$totalEarn=null;
				foreach ($passengerRequests as $key => $passengerRequest) {
					if ($passengerRequest->request_status=='Completed') {
						$bidRequest = BidRequest::where('passenger_request_id',$passengerRequest->passenger_request_id)->where('driver_id',$passengerRequest->driver_id)->first();
						if (isset($bidRequest)) {
							$totalEarn = $totalEarn+$bidRequest->bid_cost;
						}
					}
					$driver->totalEarn = $totalEarn;
				}
			}
            $totalFiltered =  User::where('user_scope', 'driver-service')
            	->where(function($q) use ($search){
	            	$q->where('first_name', 'like', "%{$search}%")
	                ->orWhere('last_name', 'like', "%{$search}%")
	                ->orWhere('isdCode','like',"%{$search}%")
	                ->orWhere('mobile','like',"%{$search}%")
	                ->orWhere('created_at','like',"%{$search}%");
            	})
            	->orWhere('user_scope', 'driver-passenger-service')
            	->where(function($q) use ($search){
	            	$q->where('first_name', 'like', "%{$search}%")
	                ->orWhere('last_name', 'like', "%{$search}%")
	                ->orWhere('isdCode','like',"%{$search}%")
	                ->orWhere('mobile','like',"%{$search}%")
	                ->orWhere('created_at','like',"%{$search}%");
            	})
				->count();
		}

		$data = array();
		
		if($drivers){
			foreach($drivers as $driver){
                $nestedData['driver_name']     = $driver->first_name." ".$driver->last_name;
				$nestedData['mobileno']   = $driver->isdCode.'-'.$driver->mobile;
				if(isset($driver->driver_profile)){
					if($driver->driver_profile->status == "approved"){
						$nestedData['status'] = '<span class="tag tag-success">'.$driver->driver_profile->status.'</span>';
					}elseif($driver->driver_profile->status == "banned"){
						$nestedData['status'] = '<span class="tag tag-danger">'.$driver->driver_profile->status.'</span>';
					}else{
						$nestedData['status'] = '<span class="tag tag-info">'.$driver->driver_profile->status.'</span>';
					}
				}else{
					$nestedData['status']   = null;
				}
				$nestedData['total_rides']  = $driver->totalRide;
				if (isset($driver->totalEarn)) {
					$nestedData['total_earn']  = '$'.$driver->totalEarn;
				}else{
					$nestedData['total_earn']  = '$0.00';
				}
				$nestedData['join_at']  = $driver->created_at->diffForHumans();
                $nestedData['action'] = '<a href="details/'.$driver->id.'" class="btn btn-info">View by Ride</a>
					<a href="detailsbybid/'.$driver->id.'" class="btn btn-info">View by Bid</a>';
               
				$data[] = $nestedData;
			}
		}
		
		$json_data = array(
			"draw"			  => intval($request->input('draw')),
			"recordsTotal"	  => intval($totalDrivers),
			"recordsFiltered" => intval($totalFiltered),
			"data"			  => $data
		);
		
		echo json_encode($json_data);
	}
	

	public function driverStatementDetails($id)
	{
		$driver = User::find($id);
		$rides = PassengerRequest::where('driver_id',$id)->get();
		//$totalEarn = null;
		$cancel_count=null;
		$percent=null;
		if (count($rides)>0) {
		foreach ($rides as $key => $ride) {
			if ($ride->request_status == 'Completed') {
				//$totalEarn = $totalEarn+$ride->earn;
				$bidRequest = BidRequest::where('passenger_request_id',$ride->passenger_request_id)->where('driver_id',$ride->driver_id)->first();
				if (isset($bidRequest)) {
					$ride->earn = $bidRequest->bid_cost;
				}
			}
			
			if ($ride->request_status == 'Cancel_By_Driver'||$ride->request_status == 'Cancel_By_Passenger') {
				$cancel_count = $cancel_count+1;
			}
			$waypoints=WaypointRequest::where('passenger_request_id', $ride->passenger_request_id)->get();
			
			foreach ($waypoints as $key => $waypoint) {
				if ($waypoint->waypoint_type=='source') {
					$ride->source_address = $waypoint->address;
				}
				if ($waypoint->waypoint_type=='destination') {
					$ride->destination_address = $waypoint->address;
				}
			}
		}
		$percent = ($cancel_count*100)/count($rides);
	}
		return view('admin.statements.driver-statement-details',compact('rides','cancel_count','percent','driver'));
	}


	public function driverStatementDetailsByBid($id)
	{
		$driver = User::find($id);
		$details_byBids = DB::select('SELECT br.passenger_request_id, br.bid_cost,br.status, br.created_at as bid_created_at, rq.* FROM bid_request br left join passenger_request rq on rq.passenger_request_id=br.passenger_request_id where br.status in("Bid_Done","Bid_Accepted_by_passenger") and br.driver_id=?',[$id]);

		if (count($details_byBids)>0) {
			foreach ($details_byBids as $key => $details_byBid) {
				$waypoints=WaypointRequest::where('passenger_request_id', $details_byBid->passenger_request_id)->get();
			
				foreach ($waypoints as $key => $waypoint) {
					if ($waypoint->waypoint_type=='source') {
						$details_byBid->source_address = $waypoint->address;
					}
					if ($waypoint->waypoint_type=='destination') {

resources/views/admin/statements/driver-statement-biddetails.blade.php
@extends('admin.layout.base')

@section('title', 'Driver details_byBid Statement')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
        	<a href="{{ route('admin.statement.driver.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>
        	
        	<h3 class="mb-1">{{$driver->first_name}}'s Overall Bid Statement - {{$driver->created_at->diffForHumans()}}</h3>

        	<div class="row">

				<div class="row row-md mb-2" style="padding: 15px;">
					<div class="col-md-12">
						<div class="box bg-white">
							<div class="box-block clearfix">
								<h5 class="float-xs-left"></h5>
								<div class="float-xs-right">
								</div>
							</div>

				            <table class="table table-striped table-bordered dataTable" id="table-2">
				                <thead>
				                   <tr>
										<td>Booking ID</td>
										<td>Picked up</td>
										<td>Dropped</td>
										<td>Booking Type</td>
										<td>Bid Date</td>
										<td>Bid Cost</td>
										<td>Action</td>
									</tr>
				                </thead>
				                <tbody>
				               
								@foreach($details_byBids as $index => $details_byBid)
								<tr>
									<td>
										{{$details_byBid->passenger_request_id}}
									</td>
									<td>
										@if($details_byBid->source_address != '')
											{{$details_byBid->source_address}}
										@else
											Not Provided
										@endif
									</td>
									<td>
										@if($details_byBid->destination_address != '')
											{{$details_byBid->destination_address}}
										@else
											Not Provided
										@endif
									</td>
									<td>
										@if($details_byBid->booking_type == "ride_now")
											<span class="tag tag-info">Ride Now</span>
										@endif
										@if($details_byBid->booking_type == "schedule_ride")
											<span class="tag tag-info">Schedule Ride</span>
										@endif
									</td>
									<td>
										<span class="text-muted">{{date('d M Y',strtotime($details_byBid->bid_created_at))}}</span>
									</td>
									<td>
										${{$details_byBid->bid_cost}}
									</td>
									<td>
										<a class="text-primary" href="{{route('admin.statement.details',[$details_byBid->passenger_request_id,'driver-bidstatement'])}}"><span class="underline1">View Ride Details</span></a>
									</td>
								</tr>
								@endforeach
								</tbody>		
				                <tfoot>
				                    <tr>
										<td>Booking ID</td>
										<td>Picked up</td>
										<td>Dropped</td>
										<td>Booking Type</td>
										<td>Bid Date</td>
										<td>Bid Cost</td>
										<td>Action</td>
									</tr>
				                </tfoot>
				            </table>
						</div>
					</div>
				</div>
        	</div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/statements/request.blade.php
@extends('admin.layout.base')

@section('title', 'Request details ')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            @if($param=='dashboard')
            <a href="{{ route('admin.dashboard.index') }}" class="btn btn-default pull-right">
                <i class="fa fa-angle-left"></i> Back
            </a>
            @endif
            @if($param=='overall')
            <a href="{{ route('admin.statement',$param) }}" class="btn btn-default pull-right">
                <i class="fa fa-angle-left"></i> Back
            </a>
            @endif
            @if($param=='driver-statement')
            <a href="{{route('admin.statement.driver.details', $driver->id)}}" class="btn btn-default pull-right">
                <i class="fa fa-angle-left"></i> Back
            </a>
            @endif
            @if($param=='driver-bidstatement')
            <a href="{{route('admin.statement.driver.detailsbybid', $driver->id)}}" class="btn btn-default pull-right">
                <i class="fa fa-angle-left"></i> Back
            </a>
            @endif
            @if($param=='today')
            <a href="{{ route('admin.statement',$param) }}" class="btn btn-default pull-right">
                <i class="fa fa-angle-left"></i> Back
            </a>
            @endif
            @if($param=='weekly')
            <a href="{{ route('admin.statement',$param) }}" class="btn btn-default pull-right">
                <i class="fa fa-angle-left"></i> Back
            </a>
            @endif
            @if($param=='monthly')
            <a href="{{ route('admin.statement',$param) }}" class="btn btn-default pull-right">
                <i class="fa fa-angle-left"></i> Back
            </a>
            @endif
            @if($param=='yearly')
            <a href="{{ route('admin.statement',$param) }}" class="btn btn-default pull-right">
                <i class="fa fa-angle-left"></i> Back
            </a>
            @endif
            <h4 style="margin-bottom: 2em;">Request details</h4>
            <div class="row">
                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-4">User Name :</dt>
                        <dd class="col-sm-8">
                            @if(isset($passenger))
                            {{ $passenger->first_name }} {{ $passenger->last_name }}
                            @else
                            Not Assigned
                            @endif
                        </dd>

                        <dt class="col-sm-4">Driver Name :</dt>
                        <dd class="col-sm-8">
                            @if(isset($driver))
                            {{ $driver->first_name }} {{ $driver->last_name }}
                            @else
                            Not Assigned
                            @endif
                        </dd>

                        <dt class="col-sm-4">Pickup Address :</dt>
                        <dd class="col-sm-8">{{ $source_address ? $source_address : '-' }}</dd>

                        <dt class="col-sm-4">Drop Address :</dt>
                        <dd class="col-sm-8">{{ $destination_address ? $destination_address : '-' }}</dd>

                        <dt class="col-sm-4">Ride Status : </dt>
                        <dd class="col-sm-8">
                            {{ $passengerRequest->request_status }}
                        </dd>

                    </dl>
                </div>
                <div class="col-md-6">
                    <div id="map"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('styles')
<style type="text/css">
    #map {
        height: 450px;
    }
</style>
@endsection

@section('scripts')
<script type="text/javascript">
    var map;
    var zoomLevel = 11;

    function initMap() {

        map = new google.maps.Map(document.getElementById('map'));

        var marker = new google.maps.Marker({
            map: map,
            //icon: '/asset/img/marker-start.png',
            anchorPoint: new google.maps.Point(0, -29)
        });

         var markerSecond = new google.maps.Marker({
            map: map,
            //icon: '/asset/img/marker-end.png',
            anchorPoint: new google.maps.Point(0, -29)
        });

        var bounds = new google.maps.LatLngBounds();

        source = new google.maps.LatLng({{ $source_lat }}, {{ $source_long }});
        destination = new google.maps.LatLng({{ $destination_lat }}, {{ $destination_long }});

        marker.setPosition(source);
        markerSecond.setPosition(destination);

        var directionsService = new google.maps.DirectionsService;
        var directionsDisplay = new google.maps.DirectionsRenderer({suppressMarkers: true, preserveViewport: true});
        directionsDisplay.setMap(map);

        directionsService.route({
            origin: source,
            destination: destination,
            travelMode: google.maps.TravelMode.DRIVING
        }, function(result, status) {
            if (status == google.maps.DirectionsStatus.OK) {
                console.log(result);
                directionsDisplay.setDirections(result);

                marker.setPosition(result.routes[0].legs[0].start_location);
                markerSecond.setPosition(result.routes[0].legs[0].end_location);
            }
        });

        @if($passengerRequest->request_status != 'Completed')
        // var markerProvider = new google.maps.Marker({
        //     map: map,
        //     icon: "/asset/img/marker-car.png",
        //     anchorPoint: new google.maps.Point(0, -29)
        // });

        // provider = new google.maps.LatLng();
        // markerProvider.setVisible(true);
        // markerProvider.setPosition(provider);
        // console.log('Provider Bounds', markerProvider.getPosition());
        // bounds.extend(markerProvider.getPosition());
        @endif

        bounds.extend(marker.getPosition());
        bounds.extend(markerSecond.getPosition());
        map.fitBounds(bounds);
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAP_KEY') }}&libraries=places&callback=initMap" async defer></script>
@endsection