routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('/login');
Route::get('/', 'Admin\Auth\LoginController@showLoginForm')->name('/');
Route::post('/loggedin', 'Admin\Auth\LoginController@login');
Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@otpRequestForm')->name('password.reset');
Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendOTP')->name('password.email');
Route::get('password/otp', 'Admin\Auth\ForgotPasswordController@otpForm')->name('password.otp');
Route::get('password/otpvarify', 'Admin\Auth\ForgotPasswordController@otpVarification')->name('password.otpvarify');
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	Route::resource('dashboard', 'Dashboard\DashboardController');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');

	Route::resource('service', 'Service\ServiceTypeController');

	Route::resource('vehicle', 'Vehicle\VehicleController');
	Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');
	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	Route::get('driver/carimages/{id}', 'Driver\DriverController@driverCarImages')->name('driver.carimages');
	Route::get('driver/transaction/{id}', 'Driver\DriverController@driverTransaction')->name('driver.transaction');
	Route::post('driver/document-reason/{id}', 'Driver\DriverController@documentVerificationReason')->name('driver.document-reason');

	Route::resource('credit', 'CreditPackage\CreditPackageController');
	Route::resource('setting', 'Setting\SettingController');
	Route::resource('email-control', 'Email\EmailController');

	//Driver Document verification.........

	Route::get('driver/check-document/{id}', 'Driver\DocumentVerificationController@allDocumentCheck')->name('driver.check-document');
	Route::get('driver/rating-review/{id}', 'Driver\DriverRatingController@driverRatingReview')->name('driver.rating-review');
	Route::get('driver/runcron/{id}', 'Driver\DocumentVerificationController@cronjobToMailDriver')->name('driver.runcron');
	//.....................................

	Route::get('driver/rating-list/{id}/{last_id}/{first_id}', 'Driver\DriverRatingController@ratingList')->name('driver.rating-list');
	Route::post('driver/reason/{id}', 'Driver\DriverController@driverInactiveBannedReason')->name('driver.reason');
	Route::get('driver/rating-search/{id}', 'Driver\DriverRatingController@searchRating')->name('driver.rating-search');

	Route::post('driver/rating-alert/{id}', 'Driver\DriverRatingController@driverRatingAlert')->name('driver.rating-alert');
	//payment
	// Route::get('payment/index', 'Payment\PaymentController@paymentList')->name('payment.index');

	Route::get('package/sales/report', 'PackageSales\PackageSalesReportController@packageSalesReport')->name('package.sales.report');
	Route::get('package/sales/report/search', 'PackageSales\PackageSalesReportController@searchPackageSalesReport')->name('package.sales.report.search');
	Route::get('package/sales/report/details/{id}', 'PackageSales\PackageSalesReportController@packageSalesReportDetails')->name('package.sales.report.details');
	Route::get('package/sales/report/detail/{id}/{from_date}/{to_date}', 'PackageSales\PackageSalesReportController@packageSalesReportDetailsBySearch')->name('package.sales.report.detail');

	//ride history
	Route::get('statement/{type}', 'Statement\StatementController@statement')->name('statement');
		//not use
		Route::get('statement/today', 'Statement\StatementController@statement_today')->name('statement.today');
		Route::get('statement/weekly', 'Statement\StatementController@statement_weekly')->name('statement.weekly');
		Route::get('statement/monthly', 'Statement\StatementController@statement_monthly')->name('statement.monthly');
		Route::get('statement/yearly', 'Statement\StatementController@statement_yearly')->name('statement.yearly');
		//not use
	Route::post('ajax-statement','Statement\StatementController@ajaxStatement')->name('ajax-statement');
	//............
	Route::get('statement/details/{id}/{param}', 'Statement\StatementController@rideDetails')->name('statement.details');

	Route::get('statement/driver/index', 'Statement\StatementController@driverStatementIndex')->name('statement.driver.index');
	Route::post('ajax-driver-statement','Statement\StatementController@ajaxDriverStatement')->name('ajax-driver-statement');
	Route::get('statement/driver/details/{id}', 'Statement\StatementController@driverStatementDetails')->name('statement.driver.details');
	Route::get('statement/driver/detailsbybid/{id}', 'Statement\StatementController@driverStatementDetailsByBid')->name('statement.driver.detailsbybid');
	
	Route::resource('promocode', 'Promocode\PromocodeController');

	Route::get('report-issue/bydriver', 'ReportIssue\ReportIssueController@reportedByDriver')->name('report-issue.bydriver');
	Route::get('report-issue/bypassenger', 'ReportIssue\ReportIssueController@reportedByPassenger')->name('report-issue.bypassenger');
	Route::get('report-issue/details/{id}/{param}', 'ReportIssue\ReportIssueController@reportIssueDetails')->name('report-issue.details');

	Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');

	Route::get('passenger/delete/{id}', 'Passenger\PassengerController@deletePassenger')->name('passenger.delete');

	Route::get('driver/delete/{id}', 'Driver\DriverController@deleteDriver')->name('driver.delete');

});

app/Http/Controllers/Admin/Driver/DocumentVerificationController.php
<?php

namespace App\Http\Controllers\Admin\Driver;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Document;
use App\Model\Driver\DriverDocuments;
use App\Model\Driver\DriverDocumentLog;
use App\User;
use Illuminate\Support\Facades\Notification;
use App\Notifications\EmailNotification;
use App\Model\Email\EmailControl;
use App\Jobs\SendEmailJob;


class DocumentVerificationController extends Controller
{
   public function allDocumentCheck($id, $isEmail=true)
   {
    $user = User::find($id);
    $documents = Document::where('status', 1)->get();
    foreach ($documents as $key => $document) {
        $document = DriverDocuments::where('user_id', $id)->where('document_id',$document->id)->first();
        if(empty($document)){
            $driver_log = DriverDocumentLog::where('user_id', $id)->first();
            if(empty($driver_log)){
                $driver_log_obj = new DriverDocumentLog;
                $driver_log_obj->user_id = $id;
                $driver_log_obj->is_all_doc_uploaded = 0;
                $driver_log_obj->is_email_fail_to_admin = 1;
                $driver_log_obj->is_email_fail_to_admin_date = date('Y-m-d H:i:s');
                $driver_log_obj->is_notify_email_driver = 1;
                $driver_log_obj->is_notify_email_driver_date = date('Y-m-d H:i:s');
                $driver_log_obj->save();
            } else {
                $driver_log->is_all_doc_uploaded = 0;
                $driver_log->is_email_fail_to_admin = 1;
                $driver_log->is_email_fail_to_admin_date = date('Y-m-d H:i:s');
                $driver_log->is_notify_email_driver = 1;
                $driver_log->is_notify_email_driver_date = date('Y-m-d H:i:s');
                $driver_log->save();
            }
            //send email
            if (isset($isEmail)) {
                $msg="Your profile is not completed, please complete your profile!";
                $sub = 'ZoomXoom Driver Profile Not Completed';
                Notification::send($user, new EmailNotification($msg,$sub));
            }

            return response(['message'=>"Driver profile not completed","data"=>[],"errors"=>array("exception"=>["Profile not completed"])],400);
        }
        
    }

    $driver_log = DriverDocumentLog::where('user_id', $id)->first();
    if(empty($driver_log)){
        $driver_log_obj = new DriverDocumentLog;
        $driver_log_obj->user_id = $id;
        $driver_log_obj->is_all_doc_uploaded = 1;
        $driver_log_obj->is_email_fail_to_admin = 0;
        $driver_log_obj->is_email_fail_to_admin_date = null;
        $driver_log_obj->is_notify_email_driver = 0;
        $driver_log_obj->is_notify_email_driver_date = null;
        $driver_log_obj->save();

    } else {
        $driver_log->is_all_doc_uploaded = 1;
        $driver_log->is_email_fail_to_admin = 0;
        $driver_log->is_email_fail_to_admin_date = null;
        $driver_log->is_notify_email_driver = 0;
        $driver_log->is_notify_email_driver_date = null;
        $driver_log->save();
    }

    $msg="New driver ".$user->first_name." ".$user->last_name." is registered successfully, please verify all the documents";
    $this->emailToAdmin($msg);
    return response(['message'=>"Driver profile completed successfully","data"=>[],"errors"=>array("exception"=>["Everything is OK."])],201);

   }

   public function emailToAdmin($msg)
   {
        $email_control = EmailControl::where('template_name','document verification')->first();
        $emails = json_decode($email_control->to_address);
        foreach ($emails as $email) {
            $admin = User::where('email',$email)->first();
            $sub = $email_control->subject;
            Notification::send($admin, new EmailNotification($msg,$sub));
        }
    }

    public function cronjobToMailDriver()
    {
        $drivers = User::where('user_scope', 'driver-service')->orWhere('user_scope', 'driver-passenger-service')->get();
        foreach ($drivers as $key => $driver) {
            $driver_log = DriverDocumentLog::where('user_id',$driver->id)->where('is_all_doc_uploaded',0)->first();
            if (isset($driver_log)) {
                $notify_email_date = $driver_log->is_notify_email_driver_date;

                $date_after_5days = date('Y-m-d H:i:s', strtotime($notify_email_date.'+5 days'));
                $date_diff = $date_after_5days<=date('Y-m-d H:i:s');

                if($date_diff) {
                    $driver_log->is_notify_email_driver_date = date('Y-m-d H:i:s');
                    $driver_log->save();
                    //send email
                    $details['email'] = $driver->email;
                    dispatch(new SendEmailJob($details));
                }
            }
        }
        // return response()->json([
        //     "success" => true,
        //     "message" => "Cron job run successfully",
        //     "errors" => array("exception"=>["Everything is OK."])
        // ],201);
    }

}

app/Http/Controllers/Api/Driver/ServiceController.php
<?php

namespace App\Http\Controllers\Api\Driver;

use App\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Model\Driver\DriverServices;
use App\Model\Driver\DriverProfiles;

class ServiceController extends Controller
{
    //
    public function toggleOnlineStatus(Request $request){
        try{

           $user_id=Auth::user()->id;
           $rule=['status' => 'required|in:active,offline,riding'];
           $validator=$this->requestValidation($request->all(),$rule);
           if($validator->status=="false"){ return response(['message'=>$validator->message,"field"=>$validator->field,"errors"=>array("exception"=>["Request Validation Failed"])],422); };
           $DriverProfiles=DriverProfiles::where("user_id",$user_id)->where("status","approved")->firstOrFail();
           $DriverServices=DriverServices::where("user_id",$user_id)->firstOrFail();
           $DriverServices->status=$request->status;
           $DriverServices->save();
           return response(['message'=>"Service status is updated","data"=>["service_status"=>$DriverServices->status],"errors"=>array("exception"=>["OK"],"e"=>[])],200);
        }
        catch(\Illuminate\Database\QueryException  $e){
            return response(['message'=>"Something went wrong","data"=>[],"errors"=>array("exception"=>["DataBase Excetion"],"e"=>$e)],500);
        }
        catch(\Illuminate\Http\Exceptions\HttpResponseException $e){
            return response(['message'=>"Something went wrong","data"=>[],"errors"=>array("exception"=>["Http Response Exception: Bad Request"])],400);
        }
        catch(ModelNotFoundException $e)
        {
            return response(['message'=>"Your account yet to be approved!.","data"=>(object)[],"errors"=>array("exception"=>["Account is not approved"])],403);
        }
    }

}

resources/views/admin/driver/carimage.blade.php
@extends('admin.layout.base')

@section('title', 'Car Images')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">Car Images</h5>
            <a href="{{ route('admin.driver.index') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-angle-left"></i> Back</a>
            <table class="table table-striped table-bordered dataTable" id="table-carimage">
                <thead>
                    <tr>
                        <th>S.No</th>
                        <th>Car Image</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($carimages as $index => $carimage)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>
                            @if(isset($carimage->image_url))
                                @if(File::exists(storage_path('app/public' .str_replace("storage", "", $carimage->image_url))))
                                    <img src="{{URL::asset($carimage->image_url)}}" style="height: 200px; width: 250px;">
                                @else
                                    <img src="{{URL::asset('asset/NO_IMG.png')}}" style="height: 50px; width: 65px;">
                                @endif
                            @else
                                <img src="{{URL::asset('asset/NO_IMG.png')}}" style="height: 50px; width: 65px;">
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>S.No</th>
                        <th>Car Image</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
$(document).ready(function(){
    $('#table-carimage').DataTable( {
        responsive: true,
        dom: 'Bfrtip',
        buttons: []
    } );
});
</script>
@endsection

resources/views/admin/driver/index.blade.php
@extends('admin.layout.base')

@section('title', 'Drivers ')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">
                Drivers
            </h5>
            <a href="{{ route('admin.driver.create') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Add New Driver</a>
            <table class="table table-striped table-bordered dataTable" id="table-driv">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Driver Name</th>
                        {{-- <th>Last Name</th> --}}
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Rating</th>
                        {{--  <th>Avg Rating</th> --}}
                        <th>Action</th>
                    </tr>
                </thead>
               {{--  <tbody>
                    @foreach($drivers as $index => $driver)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $driver->first_name }}</td>
                        <td>{{ $driver->last_name }}</td>
                        <td>{{ $driver->email }}</td>
                        <td>{{ $driver->mobile }}</td>
                        @if($driver->driver_profile != null)
                        <td>{{ $driver->driver_profile->rating }}</td>
                        @else
                        <td></td>
                        @endif --}}
                        {{-- @if($driver->passenger_request!=null)
                            @php
                            $totalRating = null;
                            @endphp
                            @foreach($driver->passenger_request as $index => $passenger_request)
                            @php
                            $totalRating = $totalRating+$passenger_request->driver_rating;
                            $index++;
                            @endphp
                            @endforeach
                            <td>{{round($totalRating/$index,2)}}</td>
                        @else
                            <td></td>
                        @endif --}}
                       {{--  <td style="line-height: 34px;">
                            <a href="{{ route('admin.driver.edit', $driver->id) }}" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>
                            <a href="{{ route('admin.drivers.document', $driver->id) }}" class="btn btn-info"><i class="fa fa-file"></i> Document</a>
                            <a href="{{ route('admin.driver.carimages', $driver->id) }}" class="btn btn-info"><i class="fa fa-file"></i> Car Images</a>
                            @if($driver->driver_profile)
                                @if($driver->driver_profile->status == 'onboarding' || $driver->driver_profile->status == 'banned')
                                <a href="{{ route('admin.driver.activation', $driver->id) }}" class="btn btn-danger driver-status" data-toggle="tooltip" data-value="Activate" data-id="{{$driver->id}}" title="Click to Active">Inactive</a>
                                @else
                                <a href="{{ route('admin.driver.activation', $driver->id) }}" class="btn btn-success driver-status" data-toggle="tooltip" data-value="Inactivate" data-id="{{$driver->id}}" title="Click to Inactive">Active</a>
                                @endif
                            @else
                            @endif
                            <a href="{{ route('admin.driver.transaction', $driver->id) }}" class="btn btn-info"><i class="fa fa-file"></i> Package</a>

                            <a href="{{ route('admin.driver.rating-review',46) }}" class="btn btn-info"><i class="fa fa-file"></i>Rating</a>
                            
                        </td>
                    </tr>
                    @endforeach
                </tbody> --}}
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Driver Name</th>
                        {{-- <th>Last Name</th> --}}
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Rating</th>
                        {{-- <th>Avg Rating</th> --}}
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

{{-- ..........Document Modal................. --}}
<div class="modal fade" id="driverModel" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-md modal-dialog-centered" role="document">
    <div class="modal-content" style="background-color: lavender;">
      <div class="modal-header">
        <h5 class="modal-title"></h5>
      </div>
      <div class="modal-body">
      
        <div class="d-flex justify-content-center">
            <div class="col-lg-12">

                <div class="alert alert-danger reason-danger" role="alert" style="display: none; height: 42px;">
                    <p class="reason-error" style="color: red; padding: 0px;"></p>
                </div>

                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="control-label text-dark">Reason</label>
                                <textarea name="reason" id="reason" rows="4" class="form-control" required></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="javascript:void(0)" class="btn btn-info float-left" id="saveReason" style="width: 70px;">
                            <span id="submit">Submit</span>
                            <i id="submit_spin" class="fa fa-circle-o-notch fa-spin" style="font-size: 20px; display: none;"></i>
                            </a>
                            <a href="" class="btn btn-secondary float-right">Close</a>
                        </div>
                    </div>
                </form>
                 
            </div>
        </div>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
{{-- end Document Modal --}}
@endsection
@section('scripts')
<script>
    $(document).ready(function(){

        $('#table-driv').DataTable( {
            "columnDefs": [{
                    'targets': [4],
                    'orderable': false
             }],
            "order": [[0, 'desc']],
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url":"{{route('admin.ajax-driver')}}",
                "dataType":"json",
                "type":"POST",
                "data":{"_token":"<?= csrf_token() ?>"}
            },
            "columns":[
                {"data":"id"},
                {"data":"driver_name"},
                {"data":"email"},
                {"data":"mobile"},
                {"data":"rating"},
                {"data":"action","searchable":false,"orderable":false}
            ],
            responsive: true,
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ],
        } );

        $(document).on('click','.driver-status',function (e) {
            e.preventDefault();
            var href = $(this).attr('href');
            var value = $(this).data('value');
            var id = $(this).data("id");
            if (value == 'Activate') {
            bootbox.confirm('Do you really want to '+value+' driver?', function (res) {
            if (res){
                window.location = href;
            }  
            });
          }
          if (value == 'Inactivate') {
            $('#driverModel').modal('show');
            $('.modal-title').html('Driver Inactivate');
            $('#saveReason').click(function(e){
              e.preventDefault()
              $.ajaxSetup({
                headers:{
                  'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
              });
              var reason = $('#reason').val();
              $('#submit').css({'display':'none'});
              $('#submit_spin').css({'display':'block'});
              $.ajax({
                url: '{{ route('admin.driver.reason',[0]) }}',
                method: 'post',
                data: { id:id, reason:reason },
                success: function(response){
                    if (response.success) {
                      $('#submit').css({'display':'block'});
                      $('#submit_spin').css({'display':'none'});
                      $('#driverModel').modal('hide');
                      window.location = href;
                    }
                },
                error: function(response){
                  $('#submit').css({'display':'block'});
                  $('#submit_spin').css({'display':'none'});
                  $('.reason-danger').show();
                  $('.reason-error').html(response.responseJSON.errors.reason);
                }
              });

            });
          }

        });

        $(document).on('click','.d-delete',function (e) {
            e.preventDefault();
            var href = $(this).attr('href');
            bootbox.confirm('Do you really want to delete?', function (res) {
            if (res){
               window.location = href;
            }
            });
        });

    });
</script>
@endsection

resources/views/admin/driver/package.blade.php
@extends('admin.layout.base')

@section('title', 'Package')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">
                Package Details
            </h5>
            <a href="{{ route('admin.driver.index') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-angle-left"></i> Back</a>
            <table class="table table-striped table-bordered dataTable" id="table-2">
                <thead>
                    <tr>
                        <th>S.No</th>
                        <th>Name</th>
                        <th>No. of Credit</th>
                        <th>Credit Remaining</th>
                        <th>Transaction ID</th>
                        <th>Transaction Status</th>
                        <th>Package Cost($)</th>
                        
                    </tr>
                </thead>
                <tbody>
                    @foreach($transaction['data']['packageDetails'] as $index => $driver)
                    <tr>
                        <td>{{$index + 1}}</td>
                        <td>{{$driver['name']}}</td>
                        <td>{{$driver['face_value']}}</td>
                        <td>{{$driver['remaining_credit']}}</td>
                        <td>{{$driver['transaction_id']}}</td>
                        <td>{{$driver['transaction_status']}}</td>
                        <td>{{$driver['transaction_cost']}}</td>
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>S.No</th>
                        <th>Name</th>
                        <th>No. of Credit</th>
                        <th>Credit Remaining</th>
                        <th>Transaction ID</th>
                        <th>Transaction Status</th>
                        <th>Package Cost($)</th>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div class="row row-md mb-2">
        <div class="col-md-12">
                <div class="box bg-white">
                    <div class="box-block clearfix">
                        <h5 class="float-xs-left">Summary</h5>
                    </div>
                    <table class="table mb-md-0 table-bordered table-hover">
                        <tbody>
                            <tr>
                                <th scope="row">Total Credit</th>
                                <td>
                                    {{$transaction['data']['totalDebitCredit']['TotalCredit_BitCredit']}}
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">Total Debit</th>
                                <td>
                                    {{$transaction['data']['totalDebitCredit']['TotalDebit_BitCredit']}}
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">Remaining Credit</th>
                                <td>
                                    {{$transaction['data']['totalDebitCredit']['remaining_credit']}}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>
@endsection